# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
variables:
 JFROG_CLI_LOG_LEVEL: 'DEBUG'

pool:
  vmImage: ubuntu-latest

steps:
- task: JFrogNpm@1
  inputs:
    command: 'install'
    artifactoryConnection: 'arti'
    sourceRepo: 'alex-npm-virtual'
    collectBuildInfo: true
    threads: '1'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

